version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    #  - ./grafana.ini:/etc/grafana/grafana.ini
    #  - ./dashboards:/etc/grafana/provisioning/dashboards
    #  - ./datasources:/etc/grafana/provisioning/datasources
    #  - ./log:/var/log/grafana
    #  - ./plugins:/var/lib/grafana/plugins
    networks:
      - app_network

volumes:
  grafana-storage: {}

networks:
  app_network:
    external: true
